local cprint = dofile("lib/cprint.lua")

cprint.print("$0White", "$f&0White", "&r$r")
cprint.print("$1Orange", "$r&1Orange", "&r$r")
cprint.print("$2Magenta", "$r&2Magenta", "&r$r")
cprint.print("$3Light Blue", "$r&3Light Blue", "&r$r")
cprint.print("$4Yellow", "$r&4Yellow", "&r$r")
cprint.print("$5Lime", "$r&5Lime", "&r$r")
cprint.print("$6Pink", "$r&6Pink", "&r$r")
cprint.print("$7Gray", "$r&7Gray", "&r$r")
cprint.print("$8Light Gray", "$r&8Light Gray", "&r$r")
cprint.print("$9Cyan", "$r&9Cyan", "&r$r")
cprint.print("$aPurple", "$r&aPurple", "&r$r")
cprint.print("$bBlue", "$r&bBlue", "&r$r")
cprint.print("$cBrown", "$r&cBrown", "&r$r")
cprint.print("$dGreen", "$r&dGreen", "&r$r")
cprint.print("$eRed", "$r&eRed&r$r")
cprint.print("&0$fBlack&r", "$r&fBlack&r$r")

term.setBackgroundColor(colours.black)
term.setTextColor(colours.white)
